### ISSUE TITLE
Option to Select Which Tags Are Added?

### ISSUE THREAD

**Issue by Magicskid** [d-fi/releases#26]
Will there be a feature implemented that allows users to select the tags they would like to add to the file? 

Also, will there be a feature that shows which tracks are explicit in the song list when you make a search from the command line?

**Comment by Kai0ken** [comment]
This would be nice, because I do not want some of the tags. So I always have to delete these tags afterwards. Wish that this gets implemented soon. 
Keep up the good work 👍 . Thanks for your efforts.

PS: Seems like something similar was asked here, but also got no response (yet): https://notabug.org/sayem314/d-fi/issues/61

**Comment by nkeor** [comment]
Let's track this on https://notabug.org/sayem314/d-fi/issues/61
